// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'addon_reminder_data_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5970352587740713152),
      name: 'AddonReminderDataModel',
      lastPropertyId: const IdUid(5, 2746755600162819742),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7232336081297131393),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 385683250195276178),
            name: 'addonId',
            type: 9,
            flags: 2048,
            indexId: const IdUid(1, 2078510235176453190))
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(3, 8874867350009558073),
      lastIndexId: const IdUid(2, 1621161587764414761),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [7860671258040706234, 8874867350009558073],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        7872167856891936808,
        2345352931768177884,
        8194163200120794815,
        2806153933844992405,
        262420994557949541,
        6274300530784901646,
        2746755600162819742
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    AddonReminderDataModel: EntityDefinition<AddonReminderDataModel>(
        model: _entities[0],
        toOneRelations: (AddonReminderDataModel object) => [],
        toManyRelations: (AddonReminderDataModel object) => {},
        getId: (AddonReminderDataModel object) => object.id,
        setId: (AddonReminderDataModel object, int id) {
          object.id = id;
        },
        objectToFB: (AddonReminderDataModel object, fb.Builder fbb) {
          final addonIdOffset = fbb.writeString(object.addonId);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, addonIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final addonIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final object =
              AddonReminderDataModel(id: idParam, addonId: addonIdParam);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [AddonReminderDataModel] entity fields to define ObjectBox queries.
class AddonReminderDataModel_ {
  /// see [AddonReminderDataModel.id]
  static final id =
      QueryIntegerProperty<AddonReminderDataModel>(_entities[0].properties[0]);

  /// see [AddonReminderDataModel.addonId]
  static final addonId =
      QueryStringProperty<AddonReminderDataModel>(_entities[0].properties[1]);
}
